spring:
  datasource:
#    url: "jdbc:mysql://192.168.1.51:3306/explore_english?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
    url: "jdbc:mysql://localhost:3306/explore_english_release?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
    username: "root"
    password: "admin"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    # 30 sec. as maximum number of milliseconds that a client will wait for a connection from the pool
    connection-timeout: 30000
    # 10 min. as the maximum amount of time that a connection is allowed to sit idle in the pool
    idle-timeout: 600000
    # 30 min. as maximum lifetime of a connection in the pool
    max-lifetime: 1800000
    connection-test-query: "SELECT 1 FROM DUAL"
    # minimum number of idle connections that HikariCP tries to maintain in the pool
    minimumIdle: 2
    # This property controls the maximum size that the pool is allowed to reach, including both idle and in-use connections.
    maximum-pool-size: 2
    # 10 sec. as the maximum amount of time that a connection will be tested for aliveness
    validation-timeout: 10000

  jpa:
    properties:
      hibernate:
        show_sql: false
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
        dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
